CREATE OR REPLACE VIEW LVE_RV_WithholdingGenerated AS 
SELECT
	wh.AD_Client_ID,
	wh.AD_Org_ID,
	ROUND(wh.A_Base_Amount * wh.CurrencyRate,wh.PricePrecision) A_Base_Amount,
	wh.C_DocType_ID,
	wh.C_InvoiceLine_ID,
	wh.C_Invoice_ID,
	wh.Created,
	wh.CreatedBy,
	wh.DateDoc,
	wh.Description,
	wh.DocAction,
	wh.DocStatus,
	wh.WHDocumentNo,
	wh.IsActive,
	wh.IsApproved,
	wh.IsDeclared,
	wh.Processed,
	wh.Processing,
	wh.SourceInvoiceLine_ID,
	wh.SourceInvoice_ID,
	wh.UUID,
	wh.Updated,
	wh.UpdatedBy,
	wh.WH_Withholding_ID,
	wh.WH_Definition_ID,
	ROUND(wh.WithholdingAmt * wh.CurrencyRate,wh.PricePrecision) WithholdingAmt,
	wh.WH_Setting_ID,
	wh.WithholdingRate,
	wh.WithholdingDeclaration_ID,
	wh.C_BPartner_ID,
	wh.IsSimulation,
	wh.SourceOrder_ID,
	wh.SourceOrderLine_ID,
	wh.IsManual,
	wh.C_Tax_ID,
	wh.WithholdingRentalRate_ID,
	wh.WithholdingVariableRate_ID,
	ROUND(wh.Subtrahend * wh.CurrencyRate,wh.PricePrecision) Subtrahend,
	wh.IsCumulativeWithholding,
	wh.WHThirdParty_ID,
	wh.IsGenerated,
	wh.TaxIndicator,
	wh.DocumentNo,
	ROUND(wh.GrandTotal * wh.CurrencyRate,wh.PricePrecision) GrandTotal,
	ROUND(wh.TotalLines * wh.CurrencyRate,wh.PricePrecision) TotalLines,
	wh.C_DocTypeTarget_ID,
	ROUND(wh.TaxBaseAmt * wh.CurrencyRate,wh.PricePrecision) TaxBaseAmt,
	ROUND(wh.TaxAmt     * wh.CurrencyRate,wh.PricePrecision) TaxAmt,
	wh.CurrencyRate,
	wh.PricePrecision,
	wh.DateAcct
FROM
(
	SELECT  wh.AD_Client_ID,
			wh.AD_Org_ID,
			wh.A_Base_Amount,
			wh.C_DocType_ID,
			wh.C_InvoiceLine_ID,
			wh.C_Invoice_ID,
			wh.Created,
			wh.CreatedBy,
			COALESCE(iw.DateAcct,wh.DateDoc) DateDoc,
			wh.Description,
			wh.DocAction,
			wh.DocStatus,
			COALESCE(iw.DocumentNo,wh.DocumentNo) WHDocumentNo,
			wh.IsActive,
			wh.IsApproved,
			wh.IsDeclared,
			wh.Processed,
			wh.Processing,
			wh.SourceInvoiceLine_ID,
			wh.SourceInvoice_ID,
			wh.UUID,
			wh.Updated,
			wh.UpdatedBy,
			wh.WH_Withholding_ID,
			wh.WH_Definition_ID,
			COALESCE(ilw.LineNetAmt,wh.WithholdingAmt) WithholdingAmt,
			wh.WH_Setting_ID,
			wh.WithholdingRate,
			wh.WithholdingDeclaration_ID,
			wh.C_BPartner_ID,
			wh.IsSimulation,
			wh.SourceOrder_ID,
			wh.SourceOrderLine_ID,
			wh.IsManual,
			wh.C_Tax_ID,
			wh.WithholdingRentalRate_ID,
			wh.WithholdingVariableRate_ID,
			wh.Subtrahend,
			wh.IsCumulativeWithholding,
			wh.WHThirdParty_ID,
			CASE WHEN iw.C_Invoice_ID IS NULL THEN 'N' ELSE 'Y' END IsGenerated,
			t.TaxIndicator,
			COALESCE(o.DocumentNo, i.DocumentNo) DocumentNo,
			COALESCE(o.GrandTotal, i.GrandTotal) GrandTotal,
			COALESCE(o.TotalLines, i.TotalLines) TotalLines,
			COALESCE(o.C_DocTypeTarget_ID, i.C_DocTypeTarget_ID) C_DocTypeTarget_ID,
			COALESCE(ot.TaxBaseAmt, it.TaxBaseAmt) TaxBaseAmt,
			COALESCE(ot.TaxAmt, it.TaxAmt) TaxAmt,
			COALESCE(CurrencyRate(COALESCE(i.C_Currency_ID, o.C_Currency_ID), COALESCE(iw.C_Currency_ID,ash.C_Currency_ID), COALESCE(i.DateAcct, o.DateAcct), COALESCE(i.C_ConversionType_ID, o.C_ConversionType_ID), COALESCE(i.AD_Client_ID, o.AD_Client_ID), COALESCE(i.AD_Org_ID, o.AD_Org_ID)),1) CurrencyRate,
			pl.PricePrecision,
			COALESCE(o.DateAcct, i.DateAcct) DateAcct
	FROM 
	WH_Withholding wh
	INNER JOIN AD_ClientInfo ci ON (wh.AD_Client_ID = ci.AD_Client_ID)
	INNER JOIN C_AcctSchema ash ON (ash.C_AcctSchema_ID = ci.C_AcctSchema1_ID)
	LEFT JOIN C_Tax t ON (wh.C_Tax_ID = t.C_Tax_ID)
	LEFT JOIN C_Order o ON (o.C_Order_ID = wh.SourceOrder_ID)
	LEFT JOIN C_OrderTax ot ON (o.C_Order_ID = ot.C_Order_ID AND ot.C_Tax_ID = wh.C_Tax_ID)  
	LEFT JOIN C_Invoice i ON (i.C_Invoice_ID = wh.SourceInvoice_ID)
	LEFT JOIN C_InvoiceTax it ON (i.C_Invoice_ID = it.C_Invoice_ID AND it.C_Tax_ID = wh.C_Tax_ID)
	LEFT JOIN C_Invoice iw ON (iw.C_Invoice_ID = wh.C_Invoice_ID AND iw.DocStatus NOT IN ('VO','RE'))
	LEFT JOIN C_InvoiceLine ilw ON (ilw.C_InvoiceLine_ID = wh.C_InvoiceLine_ID)
	LEFT JOIN M_PriceList pl ON (pl.M_PriceList_ID = COALESCE(i.M_PriceList_ID,o.M_PriceList_ID))
) AS wh;